-- Create Suppliers Table
CREATE TABLE Suppliers (
    Supplier_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Supplier_Name VARCHAR2(200) NOT NULL,
    Contact_Name VARCHAR2(200),
    Address VARCHAR2(200),
    Contact_Number VARCHAR2(20),
    Email VARCHAR2(100)
);

-- Create Orders Table
CREATE TABLE Orders (
    Order_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_Ref VARCHAR2(50) NOT NULL,
    Order_Date DATE NOT NULL,
    Supplier_ID NUMBER NOT NULL,
    Order_Total_Amount NUMBER(15, 2),
    Order_Description VARCHAR2(200),
    Order_Status VARCHAR2(50),
    CONSTRAINT fk_supplier FOREIGN KEY (Supplier_ID) REFERENCES Suppliers(Supplier_ID)
);

-- Create Order_Lines Table
CREATE TABLE Order_Lines (
    Order_Line_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_ID NUMBER NOT NULL,
    Line_Description VARCHAR2(200),
    Line_Amount NUMBER(15, 2),
    CONSTRAINT fk_order FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID)
);

-- Create Invoices Table
CREATE TABLE Invoices (
    Invoice_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Invoice_Ref VARCHAR2(50) NOT NULL,
    Invoice_Date DATE NOT NULL,
    Order_ID NUMBER NOT NULL,
    Invoice_Status VARCHAR2(50),
    Hold_Reason VARCHAR2(200),
    CONSTRAINT fk_order_invoice FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID)
);

-- Create Invoice_Lines Table
CREATE TABLE Invoice_Lines (
    Invoice_Line_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Invoice_ID NUMBER NOT NULL,
    Line_Description VARCHAR2(200),
    Line_Amount NUMBER(15, 2),
    CONSTRAINT fk_invoice FOREIGN KEY (Invoice_ID) REFERENCES Invoices(Invoice_ID)
);

-- Create Payments Table
CREATE TABLE Payments (
    Payment_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Invoice_ID NUMBER NOT NULL,
    Payment_Date DATE NOT NULL,
    Payment_Amount NUMBER(15, 2),
    Payment_Description VARCHAR2(200),
    CONSTRAINT fk_invoice_payment FOREIGN KEY (Invoice_ID) REFERENCES Invoices(Invoice_ID)
);